set sts=4
set ts=4
set sw=4
set expandtab
set autoindent
set laststatus=2

set lbr
set tw=500

set si "Smart indent
set wrap "Wrap lines

set mouse=a
set cino+=(0

set incsearch
set ignorecase
set smartcase
set hlsearch

"map q :q<enter>

nmap <silent> ,i gg=G:retab<CR>''

set pastetoggle=<F2>

:colorscheme desert

map <C-K> :ClangFormat<CR>
imap <C-K> <c-o>:ClangFormat<CR>

highligh ExtraWhitespace ctermbg=red
"highligh OverLength ctermbg=DarkMagenta ctermfg=white

" Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

au BufWinEnter * let w:m1=matchadd('ExtraWhitespace', '\s\+$', -1)

"au BufWinEnter * let w:m2=matchadd('OverLength', '\%81v.\+', -1)

set autochdir
set tags=./tags;~/workspace

syntax on

" vundle setup
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'kana/vim-operator-user'
Plugin 'davidhalter/jedi-vim'

Plugin 'yegappan/lid'
Plugin 'Valloric/YouCompleteMe'
Plugin 'rhysd/vim-clang-format'

Plugin 'rust-lang/rust.vim'
Plugin 'prabirshrestha/async.vim'
Plugin 'prabirshrestha/vim-lsp'
Plugin 'prabirshrestha/asyncomplete.vim'
Plugin 'prabirshrestha/asyncomplete-lsp.vim'
call vundle#end()

filetype plugin indent on

"Syntastic options
let g:syntastic_py_checkers = ["python3"]
let g:syntastic_check_on_open = 1

"YouCompleteMe options
let g:ycm_autoclose_preview_window_after_insertion = 1

"clang-format
autocmd FileType c ClangFormatAutoEnable

let g:clang_format#code_style = "llvm"
let g:clang_format#style_options = {
    \ "TabWidth" : 4,
    \ "UseTab" : "Never"}


function! s:insert_gates()
	let gatename = substitute(toupper(expand("%:t")), "\\.", "_", "g")
	execute "normal! i#ifndef " . gatename
	execute "normal! o#define " . gatename
	execute "normal! Go#endif /* " . gatename . " */"
	normal! kk
endfunction
autocmd BufNewFile *.{h,hpp} call <SID>insert_gates()

"rust
if executable('rls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'rls',
        \ 'cmd': {server_info->['rustup', 'run', 'nighly', 'rls']},
        \ 'whitelist': ['rust'],
        \ {)
endif
